# Site settings
title: In Coding
header-img: "https://img.alicdn.com/imgextra/i4/754328530/TB2GEa3cVXXXXbUXpXXXXXXXXXX-754328530.jpg"
tagline: "cn"
description: "A chinese man, detemined in Android and Python"
baseurl: ""
url: "http://sixwolf.net"

# About/contact
owner:
  name: " Klojure"
  email: tanglikang@163.com
  bio: "Coding Life"

# Data
gavatar: https://img.alicdn.com/imgextra/i2/754328530/TB2.khVjFXXXXagXXXXXXXXXXXX_!!754328530.jpg
favicon: img/logo.png

douban_username:  汤利康
twitter_username: SuperTwoDog
github_username: beautifulSoup
facebook_username: 汤利康
weibo_username: 不知菌
zhihu_username: 汤利康

# Build settings
# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Klojure"
      header-img: "https://img.alicdn.com/imgextra/i4/754328530/TB2GEa3cVXXXXbUXpXXXXXXXXXX-754328530.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments
comments :
  provider : duoshuo
  duoshuo :
    short_name : Klojure
  disqus :
      short_name : Klojure

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
